# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r readingData}
data<-read.csv( "activity.csv",header = TRUE)

##converting inveterl in to 00:00 time formate
##data$interval<- as.factor(sprintf("%02d:%02d", data$interval%/%100 ,data$interval%%100))

````
## What is mean total number of steps taken per day?

```{r}
library(reshape2)
dateNsteps<-data[,1:2]
data_melt<- melt(dateNsteps,id = "date")
stepsPerDay<-dcast(data_melt,date~variable,sum)
nas<-is.na(stepsPerDay$steps)
totalStepsPerDay<-stepsPerDay$steps[!nas]
hist( totalStepsPerDay, main = "Total steps per day",xlab ="Total steps per day",col ="green")
mean(stepsPerDay$steps ,na.rm =TRUE)
median(stepsPerDay$steps ,na.rm =TRUE)

```


## What is the average daily activity pattern?
```{r}
library(ggplot2)
tempdata <-data.frame(data$steps,data$interval)
names(tempdata)<-c("steps","interval")
data_melt<- melt(tempdata,id = "interval")
AverageActivity<-dcast(data_melt,interval~variable,mean,na.rm =TRUE)
g<- qplot(interval, steps, data=AverageActivity,group =1 ,geom="line") +theme(aspect.ratio = 1/2)
g+labs(title = "Average daily activity")
#g+ scale_x_discrete(breaks = AverageActivity$interval[seq(1,288, by = 6)]) 
```

## Imputing missing values

```{r}
data[is.na(data)]<-AverageActivity$steps

```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
wdays<-strptime(data$date, format= "%Y-%m-%d")
wd<-weekdays(wdays)
we <-wd =="Saturday"|wd=="Sunday"
wd[we]<-"weekends"
wd[!we]<-"weekdays"
data$date<-as.factor(wd)
data_melt<- melt(data,id = c("date","interval"))
wdayNsteps<-dcast(data_melt,date+interval~variable,mean)
library(lattice)
xyplot(steps~interval|date,data =wdayNsteps,type ="l",main ="Activtiy patterns between weekdays and weekends",layout =c(1,2))
```

